# Generated by Django 4.0.2 on 2022-02-10 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='Department',
            new_name='department',
        ),
        migrations.AddField(
            model_name='student',
            name='gender',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='subjects',
            field=models.CharField(default='computer', max_length=200),
            preserve_default=False,
        ),
    ]
